// Generated by CoffeeScript 1.7.1
  app.config(function($stateProvider, $urlRouterProvider) {
    $stateProvider.state("home", {
      url: "/home",
      templateUrl: "home.html",
      controller: "HomeController"
    });
    return $urlRouterProvider.otherwise("/home");
  });
